In [3]:
from GoogleNews import GoogleNews
from newspaper import Article
import pandas as pd

In [4]:
googlenews=GoogleNews(start='01/01/2021',end='02/01/2021')
googlenews.search('State Bank of India')
df_f=pd.DataFrame()
for i in range(1,31):
    googlenews.getpage(i)
    result=googlenews.result()
    df=pd.DataFrame(result)
    df_f=pd.concat([df,df_f])
    print(i)
    
googlenews.clear()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
'NoneType' object is not iterable
25
'NoneType' object is not iterable
26
'NoneType' object is not iterable
27
'NoneType' object is not iterable
28
'NoneType' object is not iterable
29
'NoneType' object is not iterable
30

In [5]:
googlenews=GoogleNews(start='01/01/2021',end='02/01/2021')
googlenews.search('SBI')
df_f1=pd.DataFrame()
for i in range(1,31):
    googlenews.getpage(i)
    result=googlenews.result()
    df=pd.DataFrame(result)
    df_f1=pd.concat([df,df_f1])
    print(i)
googlenews.clear()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
'NoneType' object is not iterable
16
'NoneType' object is not iterable
17
'NoneType' object is not iterable
18
'NoneType' object is not iterable
19
'NoneType' object is not iterable
20
'NoneType' object is not iterable
21
'NoneType' object is not iterable
22
'NoneType' object is not iterable
23
'NoneType' object is not iterable
24
'NoneType' object is not iterable
25
'NoneType' object is not iterable
26
'NoneType' object is not iterable
27
'NoneType' object is not iterable
28
'NoneType' object is not iterable
29
'NoneType' object is not iterable
30

In [6]:
googlenews=GoogleNews(start='01/01/2021',end='02/01/2021')
googlenews.search('State Bank Of India')
df_f2=pd.DataFrame()
for i in range(1,31):
    googlenews.getpage(i)
    result=googlenews.result()
    df=pd.DataFrame(result)
    df_f2=pd.concat([df,df_f2])
    print(i)
googlenews.clear()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
'NoneType' object is not iterable
25
'NoneType' object is not iterable
26
'NoneType' object is not iterable
27
'NoneType' object is not iterable
28
'NoneType' object is not iterable
29
'NoneType' object is not iterable
30

In [7]:
googlenews=GoogleNews(start='01/01/2021',end='02/01/2021')
googlenews.search('STATE BANK OF INDIA')
df_f3=pd.DataFrame()
for i in range(1,31):
    googlenews.getpage(i)
    result=googlenews.result()
    df=pd.DataFrame(result)
    df_f3=pd.concat([df,df_f3])
    print(i)
    
googlenews.clear()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
HTTP Error 429: Too Many Requests
17
HTTP Error 429: Too Many Requests
18
HTTP Error 429: Too Many Requests
19
HTTP Error 429: Too Many Requests
20
HTTP Error 429: Too Many Requests
21
HTTP Error 429: Too Many Requests
22
HTTP Error 429: Too Many Requests
23
HTTP Error 429: Too Many Requests
24
HTTP Error 429: Too Many Requests
25
HTTP Error 429: Too Many Requests
26
HTTP Error 429: Too Many Requests
27
HTTP Error 429: Too Many Requests
28
HTTP Error 429: Too Many Requests
29
HTTP Error 429: Too Many Requests
30

In [8]:
df=pd.concat([df_f,df_f1,df_f2,df_f3],axis=0)
df=df.drop_duplicates().sort_values(by='datetime',ascending=True)
df_final=df.copy()
df_final

,title,media,date,datetime,desc,link,img
225,Awesome: Amex Platinum $30 Monthly PayPal Credit,One Mile at a Time,01-Jan-2021,2021-01-01 00:00:00.000000,... the primary card member's $30 credit; The ...,https://onemileatatime.com/amex-platinum-paypal/,"data:image/gif;base64,R0lGODlhAQABAIAAAP//////..."
70,SBI introduces online water bill payment optio...,Times of India,01-Jan-2021,2021-01-01 00:00:00.000000,MANGALURU: The State Bank of India (SBI) intro...,https://timesofindia.indiatimes.com/city/manga...,"data:image/gif;base64,R0lGODlhAQABAIAAAP//////..."
89,Rohit Sharma Appointed India Vice-Captain For ...,India.com,01-Jan-2021,2021-01-01 00:00:00.000000,India vs Australia: The four-match series is c...,https://www.india.com/sports/rohit-sharma-appo...,"data:image/gif;base64,R0lGODlhAQABAIAAAP//////..."
58,Worldâ€™s biggest Covid vaccination to begin in ...,The Financial Express,01-Jan-2021,2021-01-01 00:00:00.000000,Covid 19 vaccination in India update: With the...,https://www.financialexpress.com/lifestyle/hea...,"data:image/gif;base64,R0lGODlhAQABAIAAAP//////..."
25,"CBI books Shakti Bhog Foods, directors for Rs ...",Business Today,02-Jan-2021,2021-01-02 00:00:00.000000,The FIR was filed on the basis of a complaint ...,https://www.businesstoday.in/current/corporate...,"data:image/gif;base64,R0lGODlhAQABAIAAAP//////..."
...,...,...,...,...,...,...,...
136,Budget 2021: FY22 disinvestment target at Rs 1...,Zee Business,01-Feb-2021,2021-02-01 00:00:00.000000,SBI share price: Stock touches 52-week high! W...,https://www.zeebiz.com/companies/news-fy22-dis...,"data:image/gif;base64,R0lGODlhAQABAIAAAP//////..."
41,Budget 2021: Bank Nifty skyrockets on privatis...,The Financial Express,01-Feb-2021,2021-02-01 00:00:00.000000,This was aided mainly by the Banking stocks wh...,https://www.financialexpress.com/budget/budget...,"data:image/gif;base64,R0lGODlhAQABAIAAAP//////..."
113,Bank Holidays in February 2021 in India: Check...,Times of India,01-Feb-2021,2021-02-01 00:00:00.000000,NEW DELHI: The Reserve Bank of India (RBI) rel...,https://timesofindia.indiatimes.com/business/i...,"data:image/gif;base64,R0lGODlhAQABAIAAAP//////..."
243,China Free Design High Quality Customized Jigs...,Global Sources,1 week ago,2021-04-26 12:01:34.088287,... Sources Summit Â· India Sources Â· South Kor...,https://www.globalsources.com/3D-jigsaw/JIgsaw...,"data:image/gif;base64,R0lGODlhAQABAIAAAP//////..."
243,China Free Design High Quality Customized Jigs...,Global Sources,1 week ago,2021-04-26 12:03:16.170708,... Sources Summit Â· India Sources Â· South Kor...,https://www.globalsources.com/3D-jigsaw/JIgsaw...,"data:image/gif;base64,R0lGODlhAQABAIAAAP//////..."

In [9]:
df_final1=df_final[df_final['date'].str.contains("Jan")].copy()

In [10]:
l=[]
df_final1=df_final1.fillna('')
for ind in range(df_final1.shape[0]):
    d={}
    try:
        article = Article(df_final1['link'].tolist()[ind])
        article.download()
        article.parse()
        article.nlp()
        d['Date']=df_final1['date'].tolist()[ind]
        d['Media']=df_final1['media'].tolist()[ind]
        d['Title']=article.title
        l.append(d)
        print("Done",ind)
        
    except:
        print(ind)
    #print(ind)
news_df=pd.DataFrame(l)
news_df.to_excel("/home/pogo/Desktop/Ba/Desktop/Books/Capstone/Phase 2/Parallel/Data/NEWS/SBI_articles_Jan.xlsx",index=0)

Done 0
Done 1
Done 2
Done 3
Done 4
Done 5
Done 6
Done 7
Done 8
Done 9
Done 10
Done 11
Done 12
Done 13
Done 14
Done 15
Done 16
Done 17
Done 18
Done 19
Done 20
Done 21
Done 22
Done 23
Done 24
Done 25
Done 26
Done 27
Done 28
Done 29
Done 30
Done 31
Done 32
Done 33
Done 34
Done 35
36
Done 37
Done 38
Done 39
Done 40
Done 41
Done 42
Done 43
Done 44
Done 45
Done 46
47
Done 48
Done 49
Done 50
Done 51
Done 52
Done 53
Done 54
Done 55
Done 56
Done 57
Done 58
Done 59
Done 60
Done 61
Done 62
Done 63
Done 64
Done 65
Done 66
Done 67
Done 68
Done 69
Done 70
Done 71
Done 72
Done 73
Done 74
Done 75
Done 76
Done 77
Done 78
Done 79
Done 80
Done 81
Done 82
Done 83
Done 84
85
Done 86
Done 87
Done 88
Done 89
Done 90
Done 91
Done 92
Done 93
Done 94
Done 95
Done 96
Done 97
Done 98
Done 99
Done 100
Done 101
Done 102
Done 103
Done 104
Done 105
Done 106
Done 107
108
Done 109
Done 110
Done 111
Done 112
Done 113
Done 114
Done 115
Done 116
Done 117
Done 118
Done 119
Done 120
Done 121
Done 122
Done 123
124
Done 125
Done 126
Done 127
Done 128
Done 129
Done 130
Done 131
Done 132
Done 133
Done 134
Done 135
Done 136
Done 137
Done 138
Done 139
Done 140
Done 141
Done 142
Done 143
Done 144
Done 145
Done 146
Done 147
Done 148
Done 149
Done 150
Done 151
Done 152
Done 153
Done 154
Done 155
156
Done 157
Done 158
Done 159
Done 160
161
Done 162
Done 163
Done 164
Done 165
Done 166
Done 167
Done 168
Done 169
Done 170
Done 171
Done 172
Done 173
Done 174
Done 175
Done 176
Done 177
Done 178
Done 179
Done 180
Done 181
Done 182
Done 183
Done 184
Done 185
Done 186
Done 187
Done 188
Done 189
Done 190
Done 191
Done 192
Done 193
Done 194
Done 195
Done 196
Done 197
Done 198
Done 199
Done 200
Done 201
Done 202
Done 203
Done 204
Done 205
Done 206
Done 207
Done 208
Done 209
Done 210
Done 211
Done 212
213
Done 214
Done 215
Done 216
Done 217
Done 218
Done 219
Done 220
Done 221
Done 222
Done 223
Done 224
Done 225
Done 226
Done 227
Done 228
Done 229
Done 230
Done 231
Done 232
Done 233
Done 234
Done 235
Done 236
Done 237
Done 238
Done 239
Done 240
Done 241
Done 242
Done 243
Done 244
Done 245
Done 246
Done 247
Done 248
Done 249
Done 250
Done 251
Done 252
Done 253
Done 254
Done 255
Done 256
Done 257
Done 258
Done 259
Done 260
261
Done 262
Done 263
Done 264
Done 265
Done 266
Done 267
Done 268
Done 269
Done 270
Done 271
Done 272
Done 273
Done 274
Done 275
Done 276
Done 277
Done 278
Done 279
Done 280
Done 281
Done 282
Done 283
Done 284
Done 285
Done 286
Done 287
Done 288
Done 289
Done 290
Done 291
Done 292
Done 293
Done 294
Done 295
Done 296
Done 297
Done 298
Done 299
Done 300
Done 301
Done 302
Done 303
Done 304
Done 305
Done 306
Done 307
Done 308
Done 309
Done 310
Done 311
Done 312
Done 313
Done 314
Done 315
Done 316
Done 317
Done 318
Done 319
Done 320
Done 321
Done 322
Done 323
Done 324
Done 325
Done 326
Done 327
Done 328
Done 329
Done 330
Done 331
Done 332
Done 333
Done 334
Done 335
Done 336
Done 337
Done 338
Done 339
Done 340
Done 341
Done 342
Done 343
Done 344
Done 345
Done 346
Done 347
Done 348
Done 349
Done 350
Done 351
Done 352
Done 353
Done 354
Done 355
356
Done 357
Done 358
Done 359
Done 360
Done 361
Done 362
Done 363
Done 364
Done 365
Done 366
Done 367
Done 368
Done 369
Done 370
Done 371
Done 372
Done 373
Done 374
Done 375
Done 376
Done 377
Done 378
Done 379
Done 380